### ISSUE TITLE
To do items before first release

### ISSUE THREAD

**Issue by wehimwich** [nvi-inc/fsl11#1]
This is list of known issues/changes needed for FSL11. It is expected that this list will be edited. Answers/comments can included in the list and/or added to the conversation.

- [x] Incorporate changes from _fsl11_ branches
- [x] Is disabling `Wayland` necessary before first reboot for all configurations and/or is there a better solution?
- [x] Is there a mouse issue on the GUI when waking from suspend that needs to be addressed/documented?
- [x] Add a proper fix for disabling suspend
- [x] Add **TIP** to disable power button action?
- [x] Update GPIB driver handling in _fsadapt_
- [x] Add setting _oper_/_prog_ default Desktop to `System X11 Default` in _fsadapt_
- [x] Update _fsadapt_ kernel version detection
- [x] Maybe we only need govt warning in _/etc/issue_, _/etc/issue.net_ ,and _/etc/gdm3/greeter.dconf-defaults_. Maybe we don't need it all. Instead maybe an option for something more generic like: "Authorized uses only. All activity may be monitored and reported." in _/etc/issue_, _/etc/issue.net_ ,and _/etc/gdm3/greeter.dconf-defaults_? (Append ` \l` , note leading space, in _/etc/issue_.) Don't select this option if you will be using CIS hardening in instructions.
- [x] Should what looks like benign error from _blank_secondary_ when blanking a disk from a different install be cleaned up or documented:
>  WARNING: VG name vg0 is used by VGs pn0HLp-aArQ-H5es-eTYQ-A02h-m8Se-oiEU19 and CTOQU6-ddjy-GM9b-yNuA-5nfS-kpgT-OusAjQ.
>   Fix duplicate VG names with vgrename uuid, a device filter, or system IDs.

(repeated several more times, maybe once per logical volume)
- [x] Test RAID scripts for more cases
Tested okay so far: normal _refresh_secondary, rejecting a foreign RAID in _refresh_secondary_, _drop_primary_, _recover_raid_ (after @jfhquick fixes)
- [x] Update RAID scripts to remove using Control-C to skip progress meter and don't display meter?
- [x] Urge caution in _refresh_secondary_ when suggesting _blank_secondary_ and _recover_raid_?
- [x] Add **NOTE** in  RAID doc about needing `mdadm -a` if too many changes have occurred to allow _recover_raid_ to work.
- [x] Add `set -e` to any RAID scripts that are missing it.
- [x] Test for BIOS and 32-bit (all combinations)
- [x] Add `python3-matplotlib` to selections
- [x] Move _pgperl_ installation from _fsadapt_ to selections
- [x] Finalize selections lists
- [x] Resolve CUPS scheduler failing on boot
If `netipp` is not disabled in _fsadapt_ there is no problem.
- [x] Merge #2?
- [x] Move other maintenance tasks to be appendix C
- [x] Make a note in document about _apt-show-upgradeable_ errors for ABI updates
- [x] In sub-step "Configure the package manager", move "Select the fastest Debian mirror from those available ... Enter any necessary HTTP proxy information (usually left blank.)" to the end of that sub-step (after choosing your country).
- [x] At the end sub-step 3 in Setup RAID add  "and select yes if prompted to write the changes to disk"
- [x] Remove _swap_ from Mount point column on Logical volumes table
In the end, it was kept there, but placed in parentheses and a different font.  Having it there gives a parallel construction to what is displayed by the partitioner, which may make comparisons easier.
- [x] Add setting up _/etc/hosts_ to Additional Steps appendix (include using aliases for other systems as the canonical name to make _ntpq_ more readable).
- [ ] Apply four above items to FSL10 as well?
- [x] Currently 191 packages and 184 MB downloading
- [x] Update documents to be for FSL11
- [x] Update CIS hardening script
- [x] Update CIS hardening for _/etc/pam.d/common-*_ update
- [x] In CIS hardening doc:
add `usermod  -L desktop` too
_sshd_config_: add `desktop` to `DenyUsers`
when creating AUID account, set home directory permissions to `0750`
- [ ] Apply items to FSL10 as well?
- [ ] Update remediation for Debian 11 benchmark
- [x] Test moving disks (ethernet setup `eno1`/`eno2`) to another machine with the same mainboard model to see if the adapter names change
Not surprisingly, moving between two machines with `X11SCA-F` mainboards, the same names (`eno1`/`eno2`) worked. Notably, moving from an `X11SCA-F` to a (very ancient) `C7SIM-Q` mainboard yielded different names (`enp0s25`/`enp2s0`), which necessitated a change in the Ethernet setup. I may have a chance soon to see if the installer will pick the different names if it is run on that hardware from scratch. ~~I suspect it will.~~ I did have a chance to try it and, again, not surprisingly it did pick the different names.
- [x] Fix/remove highlighted TODO items in installation document
- [x] Use _main_ as the default branch 
- [x] Add a warning that for VM installation that there must be at least two cores (FSL10 needs that too)
- [x] Update GPL3 copyright dates
- [x] Incorporate FS _fsl11_ branches into the FS (requires testing, especially of _python3_ scripts)
- [x] Should _prog_/_oper_ ~/.inputrc  have:
```
$include /etc/inputrc
revert-all-at-newline
```
- [x] Put a note in "Rescue Mode"  for a non-RAID systems to mount root partition (details?) instead of assembling RAID

**Comment by jfhquick** [comment]
User's last choice of desktop environment is saved in /var/lib/AccountsService/users/<username>

**Comment by jfhquick** [comment]
I went with updating all copyright dates to include 2023 for this release and changed all references to FSL10 into FSL11.

**Comment by wehimwich** [comment]
Closed by 559e1ae7a120b1b8fe17098d8e33c71800b9ad28
